//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_major_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string BookingDate { get; set; }
        public string ScheduledDate { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Customer_Service Customer_Service { get; set; }
        public virtual Location Location { get; set; }
    }
}
