//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_major_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation : Booking
    {
        public int ConsultationId { get; set; }
        public string Purpose { get; set; }
        public string Diagnosis { get; set; }
        public string Prescriptions { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
