//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_major_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string RoomName { get; set; }
        public string Type { get; set; }
        public string Equipment { get; set; }
        public string Status { get; set; }
        public string Availability { get; set; }
        public string Notes { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
